info on running go-sm and postcli
spacemeshos/testnet-guide pull request #33
Opened 2023-07-17 19:22 UTC by monikasmolarek

added info: only 1 go-sm node can run, postcli may simultaneously. + formatted the flags lists

2023-07-17 21:35 UTC, pigmej commented
But you can run multiple go-sm on the same machine. They just cannot share the same directories.

Therefore I don't understand that PR :)

2023-07-17 21:37 UTC, pigmej requested changes
Some changes are good but the main concern is invalid. You can have multiple go-sm on one machine. You can even mix them up with postcli. Some nodes may smesh, some initialize some just P2P etc.

2023-07-17 21:47 UTC, monikasmolarek commented
I actually created it right after our Dev mentioned today that you can have only one go-sm node running but 2 postcli 🤷‍♀️

2023-07-18 05:49 UTC, pigmej approved these changes

2023-07-18 06:05 UTC, merged